services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: csc-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    container_name: csc-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
