services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: csc-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: csc-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

